name: jmvo.se
description: Blogging about stuff
meta_description: "jmvo.se, Blogging about stuff"

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://localhost:4000'
author:         'Johan Olsson'

permalink:   /:title/
