name: jmvo.se
description: Life is too short to run proprietary software
meta_description: "jmvo.se, Blogging about stuff. Yeah"
baseurl: '/'

markdown: redcarpet
highlighter: pygments
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'http://localhost:4000'
author:         'Johan Olsson'

timezone: Europe/Berlin
permalink:   /:title/
